Felipe
Andres-Alvarez-V/motohub pull request #16
Opened 2023-09-12 18:48 UTC by FelipeArredond

- Created User paths controllers 
- Connected order and motorcycles 
- Cleaned up some css at users views

2023-09-12 19:14 UTC, Andres-Alvarez-V requested changes

2023-09-12 19:14 UTC, Andres-Alvarez-V commented on motohub_laravel/resources/views/user/brand/index.blade.php
> +                    {{$brand["name"]}}
brand -> getName()

2023-09-12 19:14 UTC, Andres-Alvarez-V commented on motohub_laravel/resources/views/user/brand/index.blade.php
> +                    <a href="{{ route('user.brand.show', ['id'=> $brand->getId()]) }}" class="btn btn-primary">Show</a>
getter

2023-09-12 19:14 UTC, Andres-Alvarez-V commented on motohub_laravel/resources/views/user/brand/index.blade.php
> +                    {{$brand["foundation_year"]}}
getter

2023-09-12 19:14 UTC, Andres-Alvarez-V commented on motohub_laravel/resources/views/user/brand/show.blade.php
> +        <li class="list-group-item">{{$motorcycle["name"]}}</li>
motorcycle -> getName

2023-09-12 20:49 UTC, GianSz requested changes

2023-09-12 20:49 UTC, GianSz commented on motohub_laravel/app/Http/Controllers/User/BrandController.php
> +        $viewData['title'] = 'Brands';
No es necesario mandar desde el controlador el dato $viewData['title'] ya este valor no se repite en las vistas (solo es el titulo de la pestaña), por el contrario, se puede establecer directamente en el blade. Además, haciendo esto como lo estás haciendo estás quemando el idioma en inglés.

2023-09-12 20:49 UTC, GianSz commented on motohub_laravel/app/Http/Controllers/User/MotorcycleController.php
> +use Illuminate\Contracts\View\View;
Se está usando una librería distinta de los otros controllers, la que siempre hemos usado (hasta en clase) es: "use Illuminate\View\View".

2023-09-12 20:49 UTC, GianSz commented on motohub_laravel/app/Http/Controllers/User/BrandController.php
> +use Illuminate\Contracts\View\View;
Se está usando una librería distinta de los otros controllers, la que siempre hemos usado (hasta en clase) es: "use Illuminate\View\View".

2023-09-12 20:49 UTC, GianSz commented on motohub_laravel/app/Http/Controllers/User/BrandController.php
> +        $viewData['logo_image'] = $brand->getLogoImage();
No coger todos los datos del modelo desde el controlador para luego enviarlos a la vista, mejor acceder a los datos desde la vista usando los getters.

2023-09-12 20:49 UTC, GianSz commented on motohub_laravel/app/Http/Controllers/User/MotorcycleController.php
> +        $viewData['title'] = 'Motorcycles';
No es necesario mandar desde el controlador el dato $viewData['title'] ya este valor no se repite en las vistas (solo es el titulo de la pestaña), por el contrario, se puede establecer directamente en el blade. Además, haciendo esto como lo estás haciendo estás quemando el idioma en inglés.

2023-09-12 20:49 UTC, GianSz commented on motohub_laravel/app/Http/Controllers/User/MotorcycleController.php
> +        $viewData['stock'] = $motorcycle->getStock();
No coger todos los datos del modelo desde el controlador para luego enviarlos a la vista, mejor acceder a los datos desde la vista usando los getters.

2023-09-12 20:49 UTC, GianSz commented on motohub_laravel/resources/lang/en/messages.php
> +    'show' => 'Show'
Agregar 'show' también en los demás lenguajes, no solo en inglés.

2023-09-12 20:49 UTC, GianSz commented on motohub_laravel/resources/sass/app.scss
> +}
Concatenar el string'-app' al final de el nombre de las clases personalizadas por nosotros para diferenciarlas con las clases de bootstrap.

2023-09-12 20:49 UTC, GianSz commented on motohub_laravel/resources/sass/app.scss
> +    background-color: $primary-color;
Ya existe la clase de los botones personalizada por nosotros se llama: 'btn-primary-app'

2023-09-12 20:49 UTC, GianSz commented on motohub_laravel/resources/views/user/brand/index.blade.php
> +    <h1>Brands</h1>
Está quemando texto sin usar lang.

2023-09-12 20:49 UTC, GianSz commented on motohub_laravel/resources/views/user/brand/index.blade.php
No usó la misma estructura para las views de listas de elementos. Usar la misma estructura de la view 'user.order.index' agregando o modificando los campos necesarios.

2023-09-12 20:49 UTC, GianSz commented on motohub_laravel/resources/views/user/brand/index.blade.php
> +@section('title', 'Brands')
No quemar el título.

2023-09-12 20:49 UTC, GianSz commented on motohub_laravel/resources/views/user/motorcycle/index.blade.php
> +@section('title', 'Motorcycles')
No quemar el título.

2023-09-12 20:49 UTC, GianSz commented on motohub_laravel/resources/views/user/motorcycle/index.blade.php
No usó la misma estructura para las views de listas de elementos. Usar la misma estructura de la view 'user.order.index' agregando o modificando los campos necesarios.

2023-09-12 20:49 UTC, GianSz commented on motohub_laravel/resources/views/user/motorcycle/index.blade.php
> +        <h1>Motorcycles</h1>
Está quemando texto, no usa lang.

2023-09-12 20:49 UTC, GianSz commented on motohub_laravel/resources/views/user/motorcycle/index.blade.php
> +                        class="btn btn-primary">Show</a>
Está quemando texto.

2023-09-12 20:49 UTC, GianSz commented on motohub_laravel/resources/views/user/motorcycle/show.blade.php
> +        <button type="submit" class=" btn btn-primary">Add to cart</button>
Está quemando texto, no usa lang.

2023-09-12 22:33 UTC, Andres-Alvarez-V commented on motohub_laravel/app/Http/Controllers/User/BrandController.php
> +        $viewData['title'] = 'Brands';
True

2023-09-12 22:34 UTC, Andres-Alvarez-V commented on motohub_laravel/app/Http/Controllers/User/BrandController.php
> +        $viewData['logo_image'] = $brand->getLogoImage();
True

2023-09-13 01:04 UTC, GianSz requested changes

2023-09-13 01:04 UTC, GianSz commented on motohub_laravel/resources/views/admin/brand/index.blade.php
> +                    {{$brand["name"]}}
Usar getter de brand

2023-09-13 01:04 UTC, GianSz commented on motohub_laravel/resources/views/admin/brand/index.blade.php
> +                    <p class="card-text">{{$brand["description"]}}</p>
Usar getter de brand

2023-09-13 01:04 UTC, GianSz commented on motohub_laravel/resources/views/admin/brand/index.blade.php
> +                    {{$brand["foundation_year"]}}
Usar getter de brand

2023-09-13 01:04 UTC, GianSz commented on motohub_laravel/resources/views/user/brand/index.blade.php
> +    <h1>Brands</h1>
En esta vista sigues quemando el texto sin lang :) <3

2023-09-13 01:18 UTC, merged